import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import AuthProvider from "@/Context/AuthProvider";
import Footer from "@/Components/Footer";


const urbanist = Urbanist({
    subsets: ["latin"],
    variable: "--font-urbanist",
});

export const metadata = {
    title: "NextBazar",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${urbanist.variable}  font-sans`}>
                <AuthProvider>
                    <div className="flex flex-col min-h-screen ">
                        <Navbar/>
                        <div className="flex-1">{children}</div>
                        <Footer/>
                    </div>
                </AuthProvider>
            </body>
        </html>
    );
}
