import { Urbanist } from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({
    subsets: ["latin"],
    variable: "--font-urbanist",
});

export const metadata = {
    title: "NextBazar",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${urbanist.variable}  font-sans`}>{children}</body>
        </html>
    );
}
